#!/bin/bash
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts 
#            section in config file)
#

PROJECT_NAME=$1
CODE_DIR=$2

cd $CODE_DIR

if [ -f rc_$TARGET ]; then
  make $TARGET
  make printwar APACHE_BASE_PATH=main
fi

if [[ $CODE_DIR == */branch/* ]]; then
  make clean
  source rc_branch
  make all
fi

exit $?
